name: CI/CD for RemixJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
 

      - name: Redeploy
        run: 
         cd /var/www/pizza-remixjs/ && git pull && npm install && npx prisma generate && npx prisma db push && npm run build && pm2 restart pizza
